### ISSUE TITLE
Some improvements

### ISSUE THREAD

**Issue by ytaylordev** [Adalab/modulo-2-evaluacion-intermedia-beafig#1]
Really cool job @beafig !!!

Here you have some tips to improve the exercise:

### JavaScript
- [x] Check if the `<input>` has an empty value or text.
- [x] It is not necessary to return this code: https://github.com/Adalab/modulo-2-evaluacion-intermedia-beafig/blob/d9225bf09089a723d752c3ab3f241bd0ce439cdb/js/main.js#L48

### JavaScript: good practices
- [x] Move variables and constants declarations to the top of the file.

### Good practices
- [x] Try to improve your commits messages. "Add JS" is a bit poor. "Add random number logic" is more explanatory.

### HTML

- [x] Use a `label` to define the content of the input.
- [x] Connect the label to the input using the `for` attribute of the label and the `id` of the input.

### Further challenges

Then you can improve the game as you please, here you have some ideas:

- Manage when the user hits the button and the input is empty.
- Make the input work when hitting enter key.
- Add a reset button that cleans the input, the counter, writes the initial feedback and generates a new random number to play again!
- Whatever you want!

### Call to action

Let me know if you have any doubts ;)

Go for it!!

> Do not close this issue until your teacher asks you to

**Comment by beafig** [comment]
Hi @ytaylordev!

I have solved the issues you indicated, but could you review the function 'compareNumbers( )' again?
I have added a new comparison if the input is empty, and I have added the 'counter()' function only in the cases where I want it to increase, I don't know if that would be correct. Thank you.

PS: I will try to follow your ideas and improve my game little by little

**Comment by ytaylordev** [comment]
Hi Bea, here are some improvements: 

- The counter function has a parameter that is never used: https://github.com/Adalab/modulo-2-evaluacion-intermedia-beafig/blob/005f6c3011a82af2f699db206c9575a4e368930e/js/main.js#L54
-  Also when you call them you don't pass any parameters:https://github.com/Adalab/modulo-2-evaluacion-intermedia-beafig/blob/005f6c3011a82af2f699db206c9575a4e368930e/js/main.js#L48
- The counter is usually started at zero, and is first incremented and then painted: https://github.com/Adalab/modulo-2-evaluacion-intermedia-beafig/blob/005f6c3011a82af2f699db206c9575a4e368930e/js/main.js#L55. Like this
`
count++
textCount.innerHTML = `Número de intentos: ${count}``

The rest of the improvements very good job :)
